name: Notify Pull Request
on: [pull_request]
jobs:
  hangouts:
    name: Hangouts
    runs-on: ubuntu-18.04
    steps:
    - name: Send Message
      uses: docker://wso2cellery/hangouts-action:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
